### ISSUE TITLE
jsonstat.from_file() returns error “can't multiply sequence by non-int of type 'list'

### ISSUE THREAD

**Issue by RJ1908** [26fe/jsonstat.py#1]
I'm trying to parse a json-stat file using jsonstat.py (v 0.1.7) but am getting an error.

The code below is copied from the examples on github (https://github.com/26fe/jsonstat.py/tree/master/examples-notebooks):

from __future__ import print_function
import os
import jsonstat

os.chdir(r'D:\Desktop\JSON_Stat')
url = 'http://www.cso.ie/StatbankServices/StatbankServices.svc/jsonservice/responseinstance/NQQ25'
file_name = "test02.json"
file_path = os.path.abspath(os.path.join("..","JSON_Stat", "CSO", file_name))

I added this line to deal with non-ascii characters in the file:

if os.path.exists(file_path):
    print("using already downloaded file {}".format(file_path))
else:
    print("download file and storing on disk")
    jsonstat.download(url, file_path) 

From here, I can load and pprint the data using the json module:

import json
import pprint as pp

with open(r"CSO\test02.json") as data_file:
    data = json.load(data_file)

pp.pprint(data)

... but when I try and use the jsonstat module (as specified in the examples) I get the error mentioned in the subject:

collection = jsonstat.from_file(r"D:\Desktop\JSON_Stat\CSO\test02.json")
collection
# abbreviated error message
--> 384 self.__pos2cat = self.__size * [None]
TypeError: can't multiply sequence by non-int of type 'list'

I understand what the error message itself means but, having studied the the dimensions.py module where it occurs, am stuck trying to understand why. I was able to run the sample OECD code without issue so perhaps the data itself is not formatted in the expected way, though the source site (http://www.cso.ie/webserviceclient/) states that the json-stat format is being used.

So, finally, my questions are: has anyone run into this error and resolved it? Has anyone succesfully used the jsonstat module to parse this specific data? Alternatively, any general advice towards troubleshooting this issue is welcome.

Thanks

**Comment by badosa** [comment]
CSO's JSON-stat has an issue: dimension sizes are exposed as strings instead of integers. Could this be related to the jsonstat.py issue?

**Comment by 26fe** [comment]
It can be a problem if dimension sizes are string. I will try to force a conversion in integers. 
Thank you for reporting the issue and for commenting!

**Comment by 26fe** [comment]
@RJ1908 I have upload a new version 0.0.10. It should parse correctly cso.ie datasets. There is  a regression test, so it should not break in future. 
I have added a simple jupyter [notebook for cso.ie](https://github.com/26fe/jsonstat.py/blob/master/examples-notebooks/cso_ie.ipynb). I consider this issue closed. Anyway you can reopen this issue if I have missed something.

**Comment by RJ1908** [comment]
That's great @26fe, works for me too. Thanks for all your effort!

**Comment by 26fe** [comment]
You are welcome!
